# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export loglikelihood
#' '@useDynLib fastutility, .registration = TRUE'
loglikelihood <- function(beta, data, Nindividuals, availabilities, draws, Ndraws, P) {
    .Call(`_fastutility_loglikelihood`, beta, data, Nindividuals, availabilities, draws, Ndraws, P)
}

#' @export individualLoglikelihood
individualLoglikelihood <- function(beta, data, Nindividuals, availabilities, draws, Ndraws, P) {
    .Call(`_fastutility_individualLoglikelihood`, beta, data, Nindividuals, availabilities, draws, Ndraws, P)
}

